name: twofold-whisper-server-2

on:
  workflow_dispatch:
  schedule:
    - cron: "20 8 * * *"

env:
  ACR_NAME: twofoldacr
  IMAGE_NAME: twofold-whisper-server
  VM_IP: "172.206.249.96"
  VM_USER: azureuser

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VM_IP }}
          username: ${{ env.VM_USER }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            docker login ${{ env.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
            docker pull ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
            docker stop whisper-container || true
            docker rm whisper-container || true
            docker run -d --name whisper-container \
              --restart unless-stopped \
              -p 127.0.0.1:9000:9000 \
              -e API_KEY=${{ secrets.API_KEY }} \
              -e ASR_ENGINE=faster_whisper \
              -e ASR_MODEL=distil-large-v3 \
              -e ASR_QUANTIZATION=float16 \
              -e WORKERS=4 \
              --gpus all \
              ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
