# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: whisper

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build \
          --file Dockerfile.gpu \
          --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/twofold-whisper:${{ github.sha }} \
          .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/twofold-whisper:${{ github.sha }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "twofold-whisper"
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/twofold-whisper:${{ github.sha }}
